ruby/blog/config/routes.rb
Blog::Application.routes.draw do
  root to: 'articles#index'
  resources :authors
  resources :articles
  resources :comments
end

ruby/blog/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_many :comments
end

ruby/blog/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

ruby/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

ruby/blog/app/controllers/application_controller.rb
require "ostruct"

class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    OpenStruct.new(admin?: true)
  end
  helper_method :current_user
end

ruby/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    respond_to do |format|
    	format.html
    	format.json { render json: @article}
    end
  end
end

ruby/blog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

ruby/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to @comment.article, notice: "Successfully created comment."
    else
      render :new
    end
  end
end

ruby/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/blog/app/helpers/authors_helper.rb
module AuthorsHelper
end

ruby/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/blog/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.name %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

ruby/blog/app/views/authors/show.html.erb
<h1><%= @article.name %></h1>

<p class="author"><em>by <%= @article.author.name %></em></p>

<%= simple_format @article.content %>

<p><%= link_to "Back to Articles", articles_path %></p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= comment.name %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y') %></em>
      <%= simple_format comment.content %>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render "comments/form" %>